apiVersion: batch/v1
kind: Job
metadata:
  name: demo-trace-job
spec:
  template:
    spec:
      containers:
      - name: telemetrygen
        image: public.ecr.aws/p3k6k6h3/telemetrygen:current
        imagePullPolicy: IfNotPresent
        args:
          - "traces"
          - "--otlp-endpoint"
          - "test-collector-collector:4318"
          - "--otlp-insecure"
          - "true"
          - "--otlp-http"
          - "--duration"
          - "1s"
      restartPolicy: Never
  backoffLimit: 4
